// Code generated by pigeon; DO NOT EDIT.

package feta

import (
	"bytes"
	"errors"
	"fmt"
	"io"
	"io/ioutil"
	"math"
	"os"
	"regexp"
	"sort"
	"strconv"
	"strings"
	"unicode"
	"unicode/utf8"
)

func toList(v interface{}) []interface{} {
	if v == nil {
		return nil
	}
	return v.([]interface{})
}

var g = &grammar{
	rules: []*rule{
		{
			name: "Query",
			pos:  position{line: 18, col: 1, offset: 178},
			expr: &actionExpr{
				pos: position{line: 18, col: 9, offset: 186},
				run: (*parser).callonQuery1,
				expr: &seqExpr{
					pos: position{line: 18, col: 9, offset: 186},
					exprs: []interface{}{
						&labeledExpr{
							pos:   position{line: 18, col: 9, offset: 186},
							label: "sels_",
							expr: &zeroOrMoreExpr{
								pos: position{line: 18, col: 15, offset: 192},
								expr: &ruleRefExpr{
									pos:  position{line: 18, col: 15, offset: 192},
									name: "Selector",
								},
							},
						},
						&labeledExpr{
							pos:   position{line: 18, col: 25, offset: 202},
							label: "tail",
							expr: &zeroOrOneExpr{
								pos: position{line: 18, col: 30, offset: 207},
								expr: &ruleRefExpr{
									pos:  position{line: 18, col: 30, offset: 207},
									name: "Tail",
								},
							},
						},
						&ruleRefExpr{
							pos:  position{line: 18, col: 36, offset: 213},
							name: "EOF",
						},
					},
				},
			},
		},
		{
			name: "Expression",
			pos:  position{line: 52, col: 1, offset: 815},
			expr: &actionExpr{
				pos: position{line: 52, col: 14, offset: 828},
				run: (*parser).callonExpression1,
				expr: &seqExpr{
					pos: position{line: 52, col: 14, offset: 828},
					exprs: []interface{}{
						&labeledExpr{
							pos:   position{line: 52, col: 14, offset: 828},
							label: "first",
							expr: &ruleRefExpr{
								pos:  position{line: 52, col: 20, offset: 834},
								name: "Level_A",
							},
						},
						&labeledExpr{
							pos:   position{line: 52, col: 28, offset: 842},
							label: "rest_",
							expr: &zeroOrMoreExpr{
								pos: position{line: 52, col: 34, offset: 848},
								expr: &seqExpr{
									pos: position{line: 52, col: 35, offset: 849},
									exprs: []interface{}{
										&ruleRefExpr{
											pos:  position{line: 52, col: 35, offset: 849},
											name: "Or",
										},
										&ruleRefExpr{
											pos:  position{line: 52, col: 38, offset: 852},
											name: "Level_A",
										},
									},
								},
							},
						},
					},
				},
			},
		},
		{
			name: "Or",
			pos:  position{line: 65, col: 1, offset: 1081},
			expr: &actionExpr{
				pos: position{line: 65, col: 6, offset: 1086},
				run: (*parser).callonOr1,
				expr: &litMatcher{
					pos:        position{line: 65, col: 6, offset: 1086},
					val:        "||",
					ignoreCase: false,
				},
			},
		},
		{
			name: "Level_A",
			pos:  position{line: 69, col: 1, offset: 1119},
			expr: &actionExpr{
				pos: position{line: 69, col: 11, offset: 1129},
				run: (*parser).callonLevel_A1,
				expr: &seqExpr{
					pos: position{line: 69, col: 11, offset: 1129},
					exprs: []interface{}{
						&labeledExpr{
							pos:   position{line: 69, col: 11, offset: 1129},
							label: "first",
							expr: &ruleRefExpr{
								pos:  position{line: 69, col: 17, offset: 1135},
								name: "Level_B",
							},
						},
						&labeledExpr{
							pos:   position{line: 69, col: 25, offset: 1143},
							label: "rest_",
							expr: &zeroOrMoreExpr{
								pos: position{line: 69, col: 31, offset: 1149},
								expr: &seqExpr{
									pos: position{line: 69, col: 32, offset: 1150},
									exprs: []interface{}{
										&ruleRefExpr{
											pos:  position{line: 69, col: 32, offset: 1150},
											name: "And",
										},
										&ruleRefExpr{
											pos:  position{line: 69, col: 36, offset: 1154},
											name: "Level_B",
										},
									},
								},
							},
						},
					},
				},
			},
		},
		{
			name: "And",
			pos:  position{line: 82, col: 1, offset: 1384},
			expr: &actionExpr{
				pos: position{line: 82, col: 7, offset: 1390},
				run: (*parser).callonAnd1,
				expr: &litMatcher{
					pos:        position{line: 82, col: 7, offset: 1390},
					val:        "&&",
					ignoreCase: false,
				},
			},
		},
		{
			name: "Level_B",
			pos:  position{line: 86, col: 1, offset: 1424},
			expr: &actionExpr{
				pos: position{line: 86, col: 11, offset: 1434},
				run: (*parser).callonLevel_B1,
				expr: &seqExpr{
					pos: position{line: 86, col: 11, offset: 1434},
					exprs: []interface{}{
						&labeledExpr{
							pos:   position{line: 86, col: 11, offset: 1434},
							label: "first",
							expr: &ruleRefExpr{
								pos:  position{line: 86, col: 17, offset: 1440},
								name: "Level_C",
							},
						},
						&labeledExpr{
							pos:   position{line: 86, col: 25, offset: 1448},
							label: "rest_",
							expr: &zeroOrMoreExpr{
								pos: position{line: 86, col: 31, offset: 1454},
								expr: &seqExpr{
									pos: position{line: 86, col: 32, offset: 1455},
									exprs: []interface{}{
										&ruleRefExpr{
											pos:  position{line: 86, col: 32, offset: 1455},
											name: "Comparison",
										},
										&ruleRefExpr{
											pos:  position{line: 86, col: 43, offset: 1466},
											name: "Level_C",
										},
									},
								},
							},
						},
					},
				},
			},
		},
		{
			name: "Comparison",
			pos:  position{line: 99, col: 1, offset: 1697},
			expr: &actionExpr{
				pos: position{line: 99, col: 14, offset: 1710},
				run: (*parser).callonComparison1,
				expr: &choiceExpr{
					pos: position{line: 99, col: 15, offset: 1711},
					alternatives: []interface{}{
						&litMatcher{
							pos:        position{line: 99, col: 15, offset: 1711},
							val:        "==",
							ignoreCase: false,
						},
						&litMatcher{
							pos:        position{line: 99, col: 22, offset: 1718},
							val:        "!=",
							ignoreCase: false,
						},
						&litMatcher{
							pos:        position{line: 99, col: 29, offset: 1725},
							val:        "<=",
							ignoreCase: false,
						},
						&litMatcher{
							pos:        position{line: 99, col: 36, offset: 1732},
							val:        ">=",
							ignoreCase: false,
						},
						&litMatcher{
							pos:        position{line: 99, col: 43, offset: 1739},
							val:        "<",
							ignoreCase: false,
						},
						&litMatcher{
							pos:        position{line: 99, col: 49, offset: 1745},
							val:        ">",
							ignoreCase: false,
						},
					},
				},
			},
		},
		{
			name: "Level_C",
			pos:  position{line: 115, col: 1, offset: 2038},
			expr: &actionExpr{
				pos: position{line: 115, col: 11, offset: 2048},
				run: (*parser).callonLevel_C1,
				expr: &seqExpr{
					pos: position{line: 115, col: 11, offset: 2048},
					exprs: []interface{}{
						&labeledExpr{
							pos:   position{line: 115, col: 11, offset: 2048},
							label: "first",
							expr: &ruleRefExpr{
								pos:  position{line: 115, col: 17, offset: 2054},
								name: "Level_D",
							},
						},
						&labeledExpr{
							pos:   position{line: 115, col: 25, offset: 2062},
							label: "rest_",
							expr: &zeroOrMoreExpr{
								pos: position{line: 115, col: 31, offset: 2068},
								expr: &seqExpr{
									pos: position{line: 115, col: 32, offset: 2069},
									exprs: []interface{}{
										&ruleRefExpr{
											pos:  position{line: 115, col: 32, offset: 2069},
											name: "Additive",
										},
										&ruleRefExpr{
											pos:  position{line: 115, col: 41, offset: 2078},
											name: "Level_D",
										},
									},
								},
							},
						},
					},
				},
			},
		},
		{
			name: "Additive",
			pos:  position{line: 128, col: 1, offset: 2308},
			expr: &actionExpr{
				pos: position{line: 128, col: 12, offset: 2319},
				run: (*parser).callonAdditive1,
				expr: &choiceExpr{
					pos: position{line: 128, col: 13, offset: 2320},
					alternatives: []interface{}{
						&litMatcher{
							pos:        position{line: 128, col: 13, offset: 2320},
							val:        "+",
							ignoreCase: false,
						},
						&litMatcher{
							pos:        position{line: 128, col: 19, offset: 2326},
							val:        "-",
							ignoreCase: false,
						},
					},
				},
			},
		},
		{
			name: "Level_D",
			pos:  position{line: 132, col: 1, offset: 2373},
			expr: &actionExpr{
				pos: position{line: 132, col: 11, offset: 2383},
				run: (*parser).callonLevel_D1,
				expr: &seqExpr{
					pos: position{line: 132, col: 11, offset: 2383},
					exprs: []interface{}{
						&labeledExpr{
							pos:   position{line: 132, col: 11, offset: 2383},
							label: "first",
							expr: &ruleRefExpr{
								pos:  position{line: 132, col: 17, offset: 2389},
								name: "Resolution",
							},
						},
						&labeledExpr{
							pos:   position{line: 132, col: 28, offset: 2400},
							label: "rest_",
							expr: &zeroOrMoreExpr{
								pos: position{line: 132, col: 34, offset: 2406},
								expr: &seqExpr{
									pos: position{line: 132, col: 35, offset: 2407},
									exprs: []interface{}{
										&ruleRefExpr{
											pos:  position{line: 132, col: 35, offset: 2407},
											name: "Multiplicative",
										},
										&ruleRefExpr{
											pos:  position{line: 132, col: 50, offset: 2422},
											name: "Resolution",
										},
									},
								},
							},
						},
					},
				},
			},
		},
		{
			name: "Multiplicative",
			pos:  position{line: 145, col: 1, offset: 2656},
			expr: &actionExpr{
				pos: position{line: 145, col: 18, offset: 2673},
				run: (*parser).callonMultiplicative1,
				expr: &choiceExpr{
					pos: position{line: 145, col: 19, offset: 2674},
					alternatives: []interface{}{
						&litMatcher{
							pos:        position{line: 145, col: 19, offset: 2674},
							val:        "*",
							ignoreCase: false,
						},
						&litMatcher{
							pos:        position{line: 145, col: 25, offset: 2680},
							val:        "/",
							ignoreCase: false,
						},
					},
				},
			},
		},
		{
			name: "Resolution",
			pos:  position{line: 149, col: 1, offset: 2728},
			expr: &actionExpr{
				pos: position{line: 149, col: 14, offset: 2741},
				run: (*parser).callonResolution1,
				expr: &seqExpr{
					pos: position{line: 149, col: 14, offset: 2741},
					exprs: []interface{}{
						&labeledExpr{
							pos:   position{line: 149, col: 14, offset: 2741},
							label: "first",
							expr: &ruleRefExpr{
								pos:  position{line: 149, col: 20, offset: 2747},
								name: "Value",
							},
						},
						&labeledExpr{
							pos:   position{line: 149, col: 26, offset: 2753},
							label: "rest_",
							expr: &zeroOrMoreExpr{
								pos: position{line: 149, col: 32, offset: 2759},
								expr: &ruleRefExpr{
									pos:  position{line: 149, col: 32, offset: 2759},
									name: "Resolver",
								},
							},
						},
					},
				},
			},
		},
		{
			name: "Resolver",
			pos:  position{line: 171, col: 1, offset: 3154},
			expr: &choiceExpr{
				pos: position{line: 171, col: 12, offset: 3165},
				alternatives: []interface{}{
					&ruleRefExpr{
						pos:  position{line: 171, col: 12, offset: 3165},
						name: "Attribute",
					},
					&ruleRefExpr{
						pos:  position{line: 171, col: 24, offset: 3177},
						name: "Index",
					},
				},
			},
		},
		{
			name: "Index",
			pos:  position{line: 173, col: 1, offset: 3184},
			expr: &actionExpr{
				pos: position{line: 173, col: 9, offset: 3192},
				run: (*parser).callonIndex1,
				expr: &seqExpr{
					pos: position{line: 173, col: 9, offset: 3192},
					exprs: []interface{}{
						&litMatcher{
							pos:        position{line: 173, col: 9, offset: 3192},
							val:        "[",
							ignoreCase: false,
						},
						&labeledExpr{
							pos:   position{line: 173, col: 13, offset: 3196},
							label: "expr",
							expr: &ruleRefExpr{
								pos:  position{line: 173, col: 18, offset: 3201},
								name: "Expression",
							},
						},
						&litMatcher{
							pos:        position{line: 173, col: 29, offset: 3212},
							val:        "]",
							ignoreCase: false,
						},
					},
				},
			},
		},
		{
			name: "Attribute",
			pos:  position{line: 177, col: 1, offset: 3264},
			expr: &actionExpr{
				pos: position{line: 177, col: 13, offset: 3276},
				run: (*parser).callonAttribute1,
				expr: &seqExpr{
					pos: position{line: 177, col: 13, offset: 3276},
					exprs: []interface{}{
						&litMatcher{
							pos:        position{line: 177, col: 13, offset: 3276},
							val:        ".",
							ignoreCase: false,
						},
						&labeledExpr{
							pos:   position{line: 177, col: 17, offset: 3280},
							label: "identifier",
							expr: &ruleRefExpr{
								pos:  position{line: 177, col: 28, offset: 3291},
								name: "Identifier",
							},
						},
					},
				},
			},
		},
		{
			name: "Value",
			pos:  position{line: 181, col: 1, offset: 3331},
			expr: &choiceExpr{
				pos: position{line: 181, col: 10, offset: 3340},
				alternatives: []interface{}{
					&ruleRefExpr{
						pos:  position{line: 181, col: 10, offset: 3340},
						name: "Bool",
					},
					&ruleRefExpr{
						pos:  position{line: 181, col: 17, offset: 3347},
						name: "Number",
					},
					&ruleRefExpr{
						pos:  position{line: 181, col: 26, offset: 3356},
						name: "String",
					},
					&ruleRefExpr{
						pos:  position{line: 181, col: 35, offset: 3365},
						name: "Identifier",
					},
					&ruleRefExpr{
						pos:  position{line: 181, col: 48, offset: 3378},
						name: "List",
					},
					&ruleRefExpr{
						pos:  position{line: 181, col: 55, offset: 3385},
						name: "Dict",
					},
					&actionExpr{
						pos: position{line: 181, col: 62, offset: 3392},
						run: (*parser).callonValue8,
						expr: &seqExpr{
							pos: position{line: 181, col: 62, offset: 3392},
							exprs: []interface{}{
								&litMatcher{
									pos:        position{line: 181, col: 62, offset: 3392},
									val:        "(",
									ignoreCase: false,
								},
								&labeledExpr{
									pos:   position{line: 181, col: 66, offset: 3396},
									label: "expr",
									expr: &ruleRefExpr{
										pos:  position{line: 181, col: 71, offset: 3401},
										name: "Expression",
									},
								},
								&litMatcher{
									pos:        position{line: 181, col: 82, offset: 3412},
									val:        ")",
									ignoreCase: false,
								},
							},
						},
					},
				},
			},
		},
		{
			name: "List",
			pos:  position{line: 185, col: 1, offset: 3439},
			expr: &actionExpr{
				pos: position{line: 185, col: 8, offset: 3446},
				run: (*parser).callonList1,
				expr: &seqExpr{
					pos: position{line: 185, col: 8, offset: 3446},
					exprs: []interface{}{
						&litMatcher{
							pos:        position{line: 185, col: 8, offset: 3446},
							val:        "[",
							ignoreCase: false,
						},
						&labeledExpr{
							pos:   position{line: 185, col: 12, offset: 3450},
							label: "first",
							expr: &ruleRefExpr{
								pos:  position{line: 185, col: 18, offset: 3456},
								name: "Expression",
							},
						},
						&labeledExpr{
							pos:   position{line: 185, col: 29, offset: 3467},
							label: "rest_",
							expr: &zeroOrMoreExpr{
								pos: position{line: 185, col: 35, offset: 3473},
								expr: &ruleRefExpr{
									pos:  position{line: 185, col: 35, offset: 3473},
									name: "ListElements",
								},
							},
						},
						&litMatcher{
							pos:        position{line: 185, col: 49, offset: 3487},
							val:        "]",
							ignoreCase: false,
						},
					},
				},
			},
		},
		{
			name: "ListElements",
			pos:  position{line: 195, col: 1, offset: 3662},
			expr: &actionExpr{
				pos: position{line: 195, col: 16, offset: 3677},
				run: (*parser).callonListElements1,
				expr: &seqExpr{
					pos: position{line: 195, col: 16, offset: 3677},
					exprs: []interface{}{
						&litMatcher{
							pos:        position{line: 195, col: 16, offset: 3677},
							val:        ",",
							ignoreCase: false,
						},
						&labeledExpr{
							pos:   position{line: 195, col: 20, offset: 3681},
							label: "expr",
							expr: &ruleRefExpr{
								pos:  position{line: 195, col: 25, offset: 3686},
								name: "Expression",
							},
						},
					},
				},
			},
		},
		{
			name: "Dict",
			pos:  position{line: 199, col: 1, offset: 3720},
			expr: &actionExpr{
				pos: position{line: 199, col: 8, offset: 3727},
				run: (*parser).callonDict1,
				expr: &seqExpr{
					pos: position{line: 199, col: 8, offset: 3727},
					exprs: []interface{}{
						&litMatcher{
							pos:        position{line: 199, col: 8, offset: 3727},
							val:        "{",
							ignoreCase: false,
						},
						&labeledExpr{
							pos:   position{line: 199, col: 12, offset: 3731},
							label: "first_",
							expr: &seqExpr{
								pos: position{line: 199, col: 20, offset: 3739},
								exprs: []interface{}{
									&ruleRefExpr{
										pos:  position{line: 199, col: 20, offset: 3739},
										name: "Identifier",
									},
									&litMatcher{
										pos:        position{line: 199, col: 31, offset: 3750},
										val:        ":",
										ignoreCase: false,
									},
									&ruleRefExpr{
										pos:  position{line: 199, col: 35, offset: 3754},
										name: "Expression",
									},
								},
							},
						},
						&labeledExpr{
							pos:   position{line: 199, col: 47, offset: 3766},
							label: "rest_",
							expr: &zeroOrMoreExpr{
								pos: position{line: 199, col: 53, offset: 3772},
								expr: &seqExpr{
									pos: position{line: 199, col: 54, offset: 3773},
									exprs: []interface{}{
										&litMatcher{
											pos:        position{line: 199, col: 54, offset: 3773},
											val:        ",",
											ignoreCase: false,
										},
										&ruleRefExpr{
											pos:  position{line: 199, col: 58, offset: 3777},
											name: "Identifier",
										},
										&litMatcher{
											pos:        position{line: 199, col: 69, offset: 3788},
											val:        ":",
											ignoreCase: false,
										},
										&ruleRefExpr{
											pos:  position{line: 199, col: 73, offset: 3792},
											name: "Expression",
										},
									},
								},
							},
						},
						&litMatcher{
							pos:        position{line: 199, col: 86, offset: 3805},
							val:        "}",
							ignoreCase: false,
						},
					},
				},
			},
		},
		{
			name: "Identifier",
			pos:  position{line: 211, col: 1, offset: 4088},
			expr: &actionExpr{
				pos: position{line: 211, col: 14, offset: 4101},
				run: (*parser).callonIdentifier1,
				expr: &oneOrMoreExpr{
					pos: position{line: 211, col: 14, offset: 4101},
					expr: &charClassMatcher{
						pos:        position{line: 211, col: 14, offset: 4101},
						val:        "[\\pL_]",
						chars:      []rune{'_'},
						classes:    []*unicode.RangeTable{rangeTable("L")},
						ignoreCase: false,
						inverted:   false,
					},
				},
			},
		},
		{
			name: "Bool",
			pos:  position{line: 215, col: 1, offset: 4166},
			expr: &choiceExpr{
				pos: position{line: 215, col: 8, offset: 4173},
				alternatives: []interface{}{
					&actionExpr{
						pos: position{line: 215, col: 8, offset: 4173},
						run: (*parser).callonBool2,
						expr: &litMatcher{
							pos:        position{line: 215, col: 8, offset: 4173},
							val:        "true",
							ignoreCase: true,
						},
					},
					&actionExpr{
						pos: position{line: 217, col: 5, offset: 4212},
						run: (*parser).callonBool4,
						expr: &litMatcher{
							pos:        position{line: 217, col: 5, offset: 4212},
							val:        "false",
							ignoreCase: true,
						},
					},
				},
			},
		},
		{
			name: "Number",
			pos:  position{line: 221, col: 1, offset: 4252},
			expr: &actionExpr{
				pos: position{line: 221, col: 10, offset: 4261},
				run: (*parser).callonNumber1,
				expr: &seqExpr{
					pos: position{line: 221, col: 10, offset: 4261},
					exprs: []interface{}{
						&zeroOrOneExpr{
							pos: position{line: 221, col: 10, offset: 4261},
							expr: &litMatcher{
								pos:        position{line: 221, col: 10, offset: 4261},
								val:        "-",
								ignoreCase: false,
							},
						},
						&ruleRefExpr{
							pos:  position{line: 221, col: 15, offset: 4266},
							name: "Integer",
						},
						&zeroOrOneExpr{
							pos: position{line: 221, col: 23, offset: 4274},
							expr: &seqExpr{
								pos: position{line: 221, col: 25, offset: 4276},
								exprs: []interface{}{
									&litMatcher{
										pos:        position{line: 221, col: 25, offset: 4276},
										val:        ".",
										ignoreCase: false,
									},
									&oneOrMoreExpr{
										pos: position{line: 221, col: 29, offset: 4280},
										expr: &ruleRefExpr{
											pos:  position{line: 221, col: 29, offset: 4280},
											name: "DecimalDigit",
										},
									},
								},
							},
						},
						&zeroOrOneExpr{
							pos: position{line: 221, col: 46, offset: 4297},
							expr: &ruleRefExpr{
								pos:  position{line: 221, col: 46, offset: 4297},
								name: "Exponent",
							},
						},
					},
				},
			},
		},
		{
			name: "Integer",
			pos:  position{line: 226, col: 1, offset: 4392},
			expr: &choiceExpr{
				pos: position{line: 226, col: 11, offset: 4402},
				alternatives: []interface{}{
					&litMatcher{
						pos:        position{line: 226, col: 11, offset: 4402},
						val:        "0",
						ignoreCase: false,
					},
					&seqExpr{
						pos: position{line: 226, col: 17, offset: 4408},
						exprs: []interface{}{
							&ruleRefExpr{
								pos:  position{line: 226, col: 17, offset: 4408},
								name: "NonZeroDecimalDigit",
							},
							&zeroOrMoreExpr{
								pos: position{line: 226, col: 37, offset: 4428},
								expr: &ruleRefExpr{
									pos:  position{line: 226, col: 37, offset: 4428},
									name: "DecimalDigit",
								},
							},
						},
					},
				},
			},
		},
		{
			name: "Exponent",
			pos:  position{line: 228, col: 1, offset: 4443},
			expr: &seqExpr{
				pos: position{line: 228, col: 12, offset: 4454},
				exprs: []interface{}{
					&litMatcher{
						pos:        position{line: 228, col: 12, offset: 4454},
						val:        "e",
						ignoreCase: true,
					},
					&zeroOrOneExpr{
						pos: position{line: 228, col: 17, offset: 4459},
						expr: &charClassMatcher{
							pos:        position{line: 228, col: 17, offset: 4459},
							val:        "[+-]",
							chars:      []rune{'+', '-'},
							ignoreCase: false,
							inverted:   false,
						},
					},
					&oneOrMoreExpr{
						pos: position{line: 228, col: 23, offset: 4465},
						expr: &ruleRefExpr{
							pos:  position{line: 228, col: 23, offset: 4465},
							name: "DecimalDigit",
						},
					},
				},
			},
		},
		{
			name: "DecimalDigit",
			pos:  position{line: 230, col: 1, offset: 4480},
			expr: &charClassMatcher{
				pos:        position{line: 230, col: 16, offset: 4495},
				val:        "[0-9]",
				ranges:     []rune{'0', '9'},
				ignoreCase: false,
				inverted:   false,
			},
		},
		{
			name: "NonZeroDecimalDigit",
			pos:  position{line: 232, col: 1, offset: 4502},
			expr: &charClassMatcher{
				pos:        position{line: 232, col: 23, offset: 4524},
				val:        "[1-9]",
				ranges:     []rune{'1', '9'},
				ignoreCase: false,
				inverted:   false,
			},
		},
		{
			name: "String",
			pos:  position{line: 234, col: 1, offset: 4531},
			expr: &actionExpr{
				pos: position{line: 234, col: 10, offset: 4540},
				run: (*parser).callonString1,
				expr: &seqExpr{
					pos: position{line: 234, col: 10, offset: 4540},
					exprs: []interface{}{
						&litMatcher{
							pos:        position{line: 234, col: 10, offset: 4540},
							val:        "\"",
							ignoreCase: false,
						},
						&zeroOrMoreExpr{
							pos: position{line: 234, col: 14, offset: 4544},
							expr: &choiceExpr{
								pos: position{line: 234, col: 16, offset: 4546},
								alternatives: []interface{}{
									&seqExpr{
										pos: position{line: 234, col: 16, offset: 4546},
										exprs: []interface{}{
											&notExpr{
												pos: position{line: 234, col: 16, offset: 4546},
												expr: &ruleRefExpr{
													pos:  position{line: 234, col: 17, offset: 4547},
													name: "EscapedChar",
												},
											},
											&anyMatcher{
												line: 234, col: 29, offset: 4559,
											},
										},
									},
									&seqExpr{
										pos: position{line: 234, col: 33, offset: 4563},
										exprs: []interface{}{
											&litMatcher{
												pos:        position{line: 234, col: 33, offset: 4563},
												val:        "\\",
												ignoreCase: false,
											},
											&ruleRefExpr{
												pos:  position{line: 234, col: 38, offset: 4568},
												name: "EscapeSequence",
											},
										},
									},
								},
							},
						},
						&litMatcher{
							pos:        position{line: 234, col: 56, offset: 4586},
							val:        "\"",
							ignoreCase: false,
						},
					},
				},
			},
		},
		{
			name: "EscapedChar",
			pos:  position{line: 239, col: 1, offset: 4665},
			expr: &charClassMatcher{
				pos:        position{line: 239, col: 15, offset: 4679},
				val:        "[\\x00-\\x1f\"\\\\]",
				chars:      []rune{'"', '\\'},
				ranges:     []rune{'\x00', '\x1f'},
				ignoreCase: false,
				inverted:   false,
			},
		},
		{
			name: "EscapeSequence",
			pos:  position{line: 241, col: 1, offset: 4695},
			expr: &choiceExpr{
				pos: position{line: 241, col: 18, offset: 4712},
				alternatives: []interface{}{
					&ruleRefExpr{
						pos:  position{line: 241, col: 18, offset: 4712},
						name: "SingleCharEscape",
					},
					&ruleRefExpr{
						pos:  position{line: 241, col: 37, offset: 4731},
						name: "UnicodeEscape",
					},
				},
			},
		},
		{
			name: "SingleCharEscape",
			pos:  position{line: 243, col: 1, offset: 4746},
			expr: &charClassMatcher{
				pos:        position{line: 243, col: 20, offset: 4765},
				val:        "[\"\\\\/bfnrt]",
				chars:      []rune{'"', '\\', '/', 'b', 'f', 'n', 'r', 't'},
				ignoreCase: false,
				inverted:   false,
			},
		},
		{
			name: "UnicodeEscape",
			pos:  position{line: 245, col: 1, offset: 4778},
			expr: &seqExpr{
				pos: position{line: 245, col: 17, offset: 4794},
				exprs: []interface{}{
					&litMatcher{
						pos:        position{line: 245, col: 17, offset: 4794},
						val:        "u",
						ignoreCase: false,
					},
					&ruleRefExpr{
						pos:  position{line: 245, col: 21, offset: 4798},
						name: "HexDigit",
					},
					&ruleRefExpr{
						pos:  position{line: 245, col: 30, offset: 4807},
						name: "HexDigit",
					},
					&ruleRefExpr{
						pos:  position{line: 245, col: 39, offset: 4816},
						name: "HexDigit",
					},
					&ruleRefExpr{
						pos:  position{line: 245, col: 48, offset: 4825},
						name: "HexDigit",
					},
				},
			},
		},
		{
			name: "HexDigit",
			pos:  position{line: 247, col: 1, offset: 4835},
			expr: &charClassMatcher{
				pos:        position{line: 247, col: 12, offset: 4846},
				val:        "[0-9a-f]i",
				ranges:     []rune{'0', '9', 'a', 'f'},
				ignoreCase: true,
				inverted:   false,
			},
		},
		{
			name: "Selector",
			pos:  position{line: 251, col: 1, offset: 4871},
			expr: &choiceExpr{
				pos: position{line: 251, col: 12, offset: 4882},
				alternatives: []interface{}{
					&ruleRefExpr{
						pos:  position{line: 251, col: 12, offset: 4882},
						name: "Recurse",
					},
					&ruleRefExpr{
						pos:  position{line: 251, col: 22, offset: 4892},
						name: "Relative",
					},
					&ruleRefExpr{
						pos:  position{line: 251, col: 33, offset: 4903},
						name: "Dir",
					},
					&ruleRefExpr{
						pos:  position{line: 251, col: 39, offset: 4909},
						name: "Pattern",
					},
					&ruleRefExpr{
						pos:  position{line: 251, col: 49, offset: 4919},
						name: "Filter",
					},
				},
			},
		},
		{
			name: "Tail",
			pos:  position{line: 253, col: 1, offset: 4927},
			expr: &choiceExpr{
				pos: position{line: 253, col: 8, offset: 4934},
				alternatives: []interface{}{
					&actionExpr{
						pos: position{line: 253, col: 8, offset: 4934},
						run: (*parser).callonTail2,
						expr: &seqExpr{
							pos: position{line: 253, col: 8, offset: 4934},
							exprs: []interface{}{
								&litMatcher{
									pos:        position{line: 253, col: 8, offset: 4934},
									val:        "@",
									ignoreCase: false,
								},
								&labeledExpr{
									pos:   position{line: 253, col: 12, offset: 4938},
									label: "expr",
									expr: &ruleRefExpr{
										pos:  position{line: 253, col: 17, offset: 4943},
										name: "Expression",
									},
								},
							},
						},
					},
					&actionExpr{
						pos: position{line: 256, col: 5, offset: 5026},
						run: (*parser).callonTail7,
						expr: &litMatcher{
							pos:        position{line: 256, col: 5, offset: 5026},
							val:        "@",
							ignoreCase: false,
						},
					},
				},
			},
		},
		{
			name: "Dir",
			pos:  position{line: 260, col: 1, offset: 5059},
			expr: &actionExpr{
				pos: position{line: 260, col: 7, offset: 5065},
				run: (*parser).callonDir1,
				expr: &labeledExpr{
					pos:   position{line: 260, col: 7, offset: 5065},
					label: "dirs_",
					expr: &oneOrMoreExpr{
						pos: position{line: 260, col: 13, offset: 5071},
						expr: &litMatcher{
							pos:        position{line: 260, col: 13, offset: 5071},
							val:        "/",
							ignoreCase: false,
						},
					},
				},
			},
		},
		{
			name: "Filter",
			pos:  position{line: 264, col: 1, offset: 5129},
			expr: &actionExpr{
				pos: position{line: 264, col: 10, offset: 5138},
				run: (*parser).callonFilter1,
				expr: &seqExpr{
					pos: position{line: 264, col: 10, offset: 5138},
					exprs: []interface{}{
						&litMatcher{
							pos:        position{line: 264, col: 10, offset: 5138},
							val:        "(?",
							ignoreCase: false,
						},
						&labeledExpr{
							pos:   position{line: 264, col: 15, offset: 5143},
							label: "expr",
							expr: &ruleRefExpr{
								pos:  position{line: 264, col: 20, offset: 5148},
								name: "Expression",
							},
						},
						&litMatcher{
							pos:        position{line: 264, col: 31, offset: 5159},
							val:        ")",
							ignoreCase: false,
						},
					},
				},
			},
		},
		{
			name: "Relative",
			pos:  position{line: 268, col: 1, offset: 5212},
			expr: &actionExpr{
				pos: position{line: 268, col: 12, offset: 5223},
				run: (*parser).callonRelative1,
				expr: &seqExpr{
					pos: position{line: 268, col: 12, offset: 5223},
					exprs: []interface{}{
						&labeledExpr{
							pos:   position{line: 268, col: 12, offset: 5223},
							label: "rel_",
							expr: &oneOrMoreExpr{
								pos: position{line: 268, col: 17, offset: 5228},
								expr: &litMatcher{
									pos:        position{line: 268, col: 17, offset: 5228},
									val:        ".",
									ignoreCase: false,
								},
							},
						},
						&andExpr{
							pos: position{line: 268, col: 22, offset: 5233},
							expr: &ruleRefExpr{
								pos:  position{line: 268, col: 23, offset: 5234},
								name: "OpStop",
							},
						},
					},
				},
			},
		},
		{
			name: "Recurse",
			pos:  position{line: 273, col: 1, offset: 5305},
			expr: &actionExpr{
				pos: position{line: 273, col: 11, offset: 5315},
				run: (*parser).callonRecurse1,
				expr: &litMatcher{
					pos:        position{line: 273, col: 11, offset: 5315},
					val:        "**/",
					ignoreCase: false,
				},
			},
		},
		{
			name: "Pattern",
			pos:  position{line: 278, col: 1, offset: 5382},
			expr: &actionExpr{
				pos: position{line: 278, col: 11, offset: 5392},
				run: (*parser).callonPattern1,
				expr: &oneOrMoreExpr{
					pos: position{line: 278, col: 11, offset: 5392},
					expr: &charClassMatcher{
						pos:        position{line: 278, col: 11, offset: 5392},
						val:        "[^/@(]",
						chars:      []rune{'/', '@', '('},
						ignoreCase: false,
						inverted:   true,
					},
				},
			},
		},
		{
			name: "OpStop",
			pos:  position{line: 287, col: 1, offset: 5595},
			expr: &choiceExpr{
				pos: position{line: 287, col: 10, offset: 5604},
				alternatives: []interface{}{
					&litMatcher{
						pos:        position{line: 287, col: 10, offset: 5604},
						val:        "/",
						ignoreCase: false,
					},
					&ruleRefExpr{
						pos:  position{line: 287, col: 16, offset: 5610},
						name: "EOF",
					},
					&litMatcher{
						pos:        position{line: 287, col: 22, offset: 5616},
						val:        "@",
						ignoreCase: false,
					},
				},
			},
		},
		{
			name: "EOF",
			pos:  position{line: 289, col: 1, offset: 5621},
			expr: &notExpr{
				pos: position{line: 289, col: 7, offset: 5627},
				expr: &anyMatcher{
					line: 289, col: 8, offset: 5628,
				},
			},
		},
	},
}

func (c *current) onQuery1(sels_, tail interface{}) (interface{}, error) {
	sels := toList(sels_)
	length := len(sels)
	var last selector
	if tail != nil {
		last = tail.(selector)
	}
	if length == 0 {
		return (&relSel{count: 1, next: last}), nil
	}
	for i := length - 1; i >= 0; i-- {
		sel := sels[i].(selector)
		sel.setNext(last)
		last = sel
	}
	switch first := sels[0].(type) {
	case *dirSel:
		Log("Parser: added root op")
		if first.count == 1 {
			sel := &rootSel{}
			sel.setNext(last)
			last = sel
		}
	case *patternSel:
		Log("Parser: added dir op")
		sel := &dirSel{}
		sel.setNext(last)
		last = sel
	}
	return last, nil
}

func (p *parser) callonQuery1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onQuery1(stack["sels_"], stack["tail"])
}

func (c *current) onExpression1(first, rest_ interface{}) (interface{}, error) {
	left := first.(fExpr)
	rest := toList(rest_)
	for _, comp_ := range rest {
		comp := toList(comp_)
		node := comp[0].(*orNode)
		node.left = left
		node.right = comp[1].(fExpr)
		left = node
	}
	return left, nil
}

func (p *parser) callonExpression1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onExpression1(stack["first"], stack["rest_"])
}

func (c *current) onOr1() (interface{}, error) {
	return &orNode{}, nil
}

func (p *parser) callonOr1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onOr1()
}

func (c *current) onLevel_A1(first, rest_ interface{}) (interface{}, error) {
	left := first.(fExpr)
	rest := toList(rest_)
	for _, comp_ := range rest {
		comp := toList(comp_)
		node := comp[0].(*andNode)
		node.left = left
		node.right = comp[1].(fExpr)
		left = node
	}
	return left, nil
}

func (p *parser) callonLevel_A1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onLevel_A1(stack["first"], stack["rest_"])
}

func (c *current) onAnd1() (interface{}, error) {
	return &andNode{}, nil
}

func (p *parser) callonAnd1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onAnd1()
}

func (c *current) onLevel_B1(first, rest_ interface{}) (interface{}, error) {
	left := first.(fExpr)
	rest := toList(rest_)
	for _, comp_ := range rest {
		comp := toList(comp_)
		node := comp[0].(*compNode)
		node.left = left
		node.right = comp[1].(fExpr)
		left = node
	}
	return left, nil
}

func (p *parser) callonLevel_B1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onLevel_B1(stack["first"], stack["rest_"])
}

func (c *current) onComparison1() (interface{}, error) {
	switch string(c.text) {
	case "==":
		return &compNode{op: EQ}, nil
	case "!=":
		return &compNode{op: NEQ}, nil
	case "<=":
		return &compNode{op: LEEQ}, nil
	case ">=":
		return &compNode{op: GREQ}, nil
	case "<":
		return &compNode{op: LE}, nil
	}
	return &compNode{op: GR}, nil
}

func (p *parser) callonComparison1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onComparison1()
}

func (c *current) onLevel_C1(first, rest_ interface{}) (interface{}, error) {
	left := first.(fExpr)
	rest := toList(rest_)
	for _, comp_ := range rest {
		comp := toList(comp_)
		node := comp[0].(*addNode)
		node.left = left
		node.right = comp[1].(fExpr)
		left = node
	}
	return left, nil
}

func (p *parser) callonLevel_C1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onLevel_C1(stack["first"], stack["rest_"])
}

func (c *current) onAdditive1() (interface{}, error) {
	return &addNode{op: c.text[0]}, nil
}

func (p *parser) callonAdditive1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onAdditive1()
}

func (c *current) onLevel_D1(first, rest_ interface{}) (interface{}, error) {
	left := first.(fExpr)
	rest := toList(rest_)
	for _, comp_ := range rest {
		comp := toList(comp_)
		node := comp[0].(*multNode)
		node.left = left
		node.right = comp[1].(fExpr)
		left = node
	}
	return left, nil
}

func (p *parser) callonLevel_D1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onLevel_D1(stack["first"], stack["rest_"])
}

func (c *current) onMultiplicative1() (interface{}, error) {
	return &multNode{op: c.text[0]}, nil
}

func (p *parser) callonMultiplicative1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onMultiplicative1()
}

func (c *current) onResolution1(first, rest_ interface{}) (interface{}, error) {
	rest := toList(rest_)
	if len(rest) == 0 {
		return first, nil
	}
	var last resolver
	for i := len(rest) - 1; i >= 0; i-- {
		node := rest[i].(resolver)
		node.setNext(last)
		last = node
	}
	switch f := first.(type) {
	case *attribRes:
		f.setNext(last)
		return f, nil
	default:
		first = &valueRes{expr: first.(fExpr)}
	}
	first.(resolver).setNext(last)
	return first.(fExpr), nil
}

func (p *parser) callonResolution1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onResolution1(stack["first"], stack["rest_"])
}

func (c *current) onIndex1(expr interface{}) (interface{}, error) {
	return &indexRes{expr: expr.(fExpr)}, nil
}

func (p *parser) callonIndex1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onIndex1(stack["expr"])
}

func (c *current) onAttribute1(identifier interface{}) (interface{}, error) {
	return identifier, nil
}

func (p *parser) callonAttribute1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onAttribute1(stack["identifier"])
}

func (c *current) onValue8(expr interface{}) (interface{}, error) {
	return expr, nil
}

func (p *parser) callonValue8() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onValue8(stack["expr"])
}

func (c *current) onList1(first, rest_ interface{}) (interface{}, error) {
	rest := toList(rest_)
	list := make([]fExpr, len(rest)+1)
	list[0] = first.(fExpr)
	for i, elm := range rest {
		list[i+1] = elm.(fExpr)
	}
	return fList(list), nil
}

func (p *parser) callonList1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onList1(stack["first"], stack["rest_"])
}

func (c *current) onListElements1(expr interface{}) (interface{}, error) {
	return expr, nil
}

func (p *parser) callonListElements1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onListElements1(stack["expr"])
}

func (c *current) onDict1(first_, rest_ interface{}) (interface{}, error) {
	first := toList(first_)
	rest := toList(rest_)
	dict := make(map[string]fExpr)
	dict[first[0].(*attribRes).identifier] = first[2].(fExpr)
	for _, kvp_ := range rest {
		kvp := toList(kvp_)
		dict[kvp[1].(*attribRes).identifier] = kvp[3].(fExpr)
	}
	return fDict(dict), nil
}

func (p *parser) callonDict1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onDict1(stack["first_"], stack["rest_"])
}

func (c *current) onIdentifier1() (interface{}, error) {
	return &attribRes{identifier: string(c.text)}, nil
}

func (p *parser) callonIdentifier1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onIdentifier1()
}

func (c *current) onBool2() (interface{}, error) {
	return fBool(true), nil
}

func (p *parser) callonBool2() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onBool2()
}

func (c *current) onBool4() (interface{}, error) {
	return fBool(false), nil
}

func (p *parser) callonBool4() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onBool4()
}

func (c *current) onNumber1() (interface{}, error) {
	n, err := strconv.ParseFloat(string(c.text), 64)
	return fNumber(n), err
}

func (p *parser) callonNumber1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onNumber1()
}

func (c *current) onString1() (interface{}, error) {
	s, err := strconv.Unquote(string(c.text))
	return fString(s), err
}

func (p *parser) callonString1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onString1()
}

func (c *current) onTail2(expr interface{}) (interface{}, error) {
	Log("Parser: in tail")
	return &tailSel{expr: expr.(fExpr)}, nil
}

func (p *parser) callonTail2() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onTail2(stack["expr"])
}

func (c *current) onTail7() (interface{}, error) {
	return &tailSel{}, nil
}

func (p *parser) callonTail7() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onTail7()
}

func (c *current) onDir1(dirs_ interface{}) (interface{}, error) {
	return &dirSel{count: len(toList(dirs_))}, nil
}

func (p *parser) callonDir1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onDir1(stack["dirs_"])
}

func (c *current) onFilter1(expr interface{}) (interface{}, error) {
	return &filterSel{expr: expr.(fExpr)}, nil
}

func (p *parser) callonFilter1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onFilter1(stack["expr"])
}

func (c *current) onRelative1(rel_ interface{}) (interface{}, error) {
	rel := toList(rel_)
	return &relSel{count: len(rel)}, nil
}

func (p *parser) callonRelative1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onRelative1(stack["rel_"])
}

func (c *current) onRecurse1() (interface{}, error) {
	Log("Parser: in 'recurse'")
	return &recurseSel{}, nil
}

func (p *parser) callonRecurse1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onRecurse1()
}

func (c *current) onPattern1() (interface{}, error) {
	Log("Parser: in 'pattern'")
	p := regexp.QuoteMeta(string(c.text))
	p = strings.ReplaceAll(p, "\\*", ".*")
	p = "^" + p + "$"
	op := &patternSel{rex: regexp.MustCompile(p)}
	return op, nil
}

func (p *parser) callonPattern1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onPattern1()
}

var (
	// errNoRule is returned when the grammar to parse has no rule.
	errNoRule = errors.New("grammar has no rule")

	// errInvalidEntrypoint is returned when the specified entrypoint rule
	// does not exit.
	errInvalidEntrypoint = errors.New("invalid entrypoint")

	// errInvalidEncoding is returned when the source is not properly
	// utf8-encoded.
	errInvalidEncoding = errors.New("invalid encoding")

	// errMaxExprCnt is used to signal that the maximum number of
	// expressions have been parsed.
	errMaxExprCnt = errors.New("max number of expresssions parsed")
)

// Option is a function that can set an option on the parser. It returns
// the previous setting as an Option.
type Option func(*parser) Option

// MaxExpressions creates an Option to stop parsing after the provided
// number of expressions have been parsed, if the value is 0 then the parser will
// parse for as many steps as needed (possibly an infinite number).
//
// The default for maxExprCnt is 0.
func MaxExpressions(maxExprCnt uint64) Option {
	return func(p *parser) Option {
		oldMaxExprCnt := p.maxExprCnt
		p.maxExprCnt = maxExprCnt
		return MaxExpressions(oldMaxExprCnt)
	}
}

// Entrypoint creates an Option to set the rule name to use as entrypoint.
// The rule name must have been specified in the -alternate-entrypoints
// if generating the parser with the -optimize-grammar flag, otherwise
// it may have been optimized out. Passing an empty string sets the
// entrypoint to the first rule in the grammar.
//
// The default is to start parsing at the first rule in the grammar.
func Entrypoint(ruleName string) Option {
	return func(p *parser) Option {
		oldEntrypoint := p.entrypoint
		p.entrypoint = ruleName
		if ruleName == "" {
			p.entrypoint = g.rules[0].name
		}
		return Entrypoint(oldEntrypoint)
	}
}

// Statistics adds a user provided Stats struct to the parser to allow
// the user to process the results after the parsing has finished.
// Also the key for the "no match" counter is set.
//
// Example usage:
//
//     input := "input"
//     stats := Stats{}
//     _, err := Parse("input-file", []byte(input), Statistics(&stats, "no match"))
//     if err != nil {
//         log.Panicln(err)
//     }
//     b, err := json.MarshalIndent(stats.ChoiceAltCnt, "", "  ")
//     if err != nil {
//         log.Panicln(err)
//     }
//     fmt.Println(string(b))
//
func Statistics(stats *Stats, choiceNoMatch string) Option {
	return func(p *parser) Option {
		oldStats := p.Stats
		p.Stats = stats
		oldChoiceNoMatch := p.choiceNoMatch
		p.choiceNoMatch = choiceNoMatch
		if p.Stats.ChoiceAltCnt == nil {
			p.Stats.ChoiceAltCnt = make(map[string]map[string]int)
		}
		return Statistics(oldStats, oldChoiceNoMatch)
	}
}

// Debug creates an Option to set the debug flag to b. When set to true,
// debugging information is printed to stdout while parsing.
//
// The default is false.
func Debug(b bool) Option {
	return func(p *parser) Option {
		old := p.debug
		p.debug = b
		return Debug(old)
	}
}

// Memoize creates an Option to set the memoize flag to b. When set to true,
// the parser will cache all results so each expression is evaluated only
// once. This guarantees linear parsing time even for pathological cases,
// at the expense of more memory and slower times for typical cases.
//
// The default is false.
func Memoize(b bool) Option {
	return func(p *parser) Option {
		old := p.memoize
		p.memoize = b
		return Memoize(old)
	}
}

// AllowInvalidUTF8 creates an Option to allow invalid UTF-8 bytes.
// Every invalid UTF-8 byte is treated as a utf8.RuneError (U+FFFD)
// by character class matchers and is matched by the any matcher.
// The returned matched value, c.text and c.offset are NOT affected.
//
// The default is false.
func AllowInvalidUTF8(b bool) Option {
	return func(p *parser) Option {
		old := p.allowInvalidUTF8
		p.allowInvalidUTF8 = b
		return AllowInvalidUTF8(old)
	}
}

// Recover creates an Option to set the recover flag to b. When set to
// true, this causes the parser to recover from panics and convert it
// to an error. Setting it to false can be useful while debugging to
// access the full stack trace.
//
// The default is true.
func Recover(b bool) Option {
	return func(p *parser) Option {
		old := p.recover
		p.recover = b
		return Recover(old)
	}
}

// GlobalStore creates an Option to set a key to a certain value in
// the globalStore.
func GlobalStore(key string, value interface{}) Option {
	return func(p *parser) Option {
		old := p.cur.globalStore[key]
		p.cur.globalStore[key] = value
		return GlobalStore(key, old)
	}
}

// InitState creates an Option to set a key to a certain value in
// the global "state" store.
func InitState(key string, value interface{}) Option {
	return func(p *parser) Option {
		old := p.cur.state[key]
		p.cur.state[key] = value
		return InitState(key, old)
	}
}

// ParseFile parses the file identified by filename.
func ParseFile(filename string, opts ...Option) (i interface{}, err error) {
	f, err := os.Open(filename)
	if err != nil {
		return nil, err
	}
	defer func() {
		if closeErr := f.Close(); closeErr != nil {
			err = closeErr
		}
	}()
	return ParseReader(filename, f, opts...)
}

// ParseReader parses the data from r using filename as information in the
// error messages.
func ParseReader(filename string, r io.Reader, opts ...Option) (interface{}, error) {
	b, err := ioutil.ReadAll(r)
	if err != nil {
		return nil, err
	}

	return Parse(filename, b, opts...)
}

// Parse parses the data from b using filename as information in the
// error messages.
func Parse(filename string, b []byte, opts ...Option) (interface{}, error) {
	return newParser(filename, b, opts...).parse(g)
}

// position records a position in the text.
type position struct {
	line, col, offset int
}

func (p position) String() string {
	return fmt.Sprintf("%d:%d [%d]", p.line, p.col, p.offset)
}

// savepoint stores all state required to go back to this point in the
// parser.
type savepoint struct {
	position
	rn rune
	w  int
}

type current struct {
	pos  position // start position of the match
	text []byte   // raw text of the match

	// state is a store for arbitrary key,value pairs that the user wants to be
	// tied to the backtracking of the parser.
	// This is always rolled back if a parsing rule fails.
	state storeDict

	// globalStore is a general store for the user to store arbitrary key-value
	// pairs that they need to manage and that they do not want tied to the
	// backtracking of the parser. This is only modified by the user and never
	// rolled back by the parser. It is always up to the user to keep this in a
	// consistent state.
	globalStore storeDict
}

type storeDict map[string]interface{}

// the AST types...

type grammar struct {
	pos   position
	rules []*rule
}

type rule struct {
	pos         position
	name        string
	displayName string
	expr        interface{}
}

type choiceExpr struct {
	pos          position
	alternatives []interface{}
}

type actionExpr struct {
	pos  position
	expr interface{}
	run  func(*parser) (interface{}, error)
}

type recoveryExpr struct {
	pos          position
	expr         interface{}
	recoverExpr  interface{}
	failureLabel []string
}

type seqExpr struct {
	pos   position
	exprs []interface{}
}

type throwExpr struct {
	pos   position
	label string
}

type labeledExpr struct {
	pos   position
	label string
	expr  interface{}
}

type expr struct {
	pos  position
	expr interface{}
}

type andExpr expr
type notExpr expr
type zeroOrOneExpr expr
type zeroOrMoreExpr expr
type oneOrMoreExpr expr

type ruleRefExpr struct {
	pos  position
	name string
}

type stateCodeExpr struct {
	pos position
	run func(*parser) error
}

type andCodeExpr struct {
	pos position
	run func(*parser) (bool, error)
}

type notCodeExpr struct {
	pos position
	run func(*parser) (bool, error)
}

type litMatcher struct {
	pos        position
	val        string
	ignoreCase bool
}

type charClassMatcher struct {
	pos             position
	val             string
	basicLatinChars [128]bool
	chars           []rune
	ranges          []rune
	classes         []*unicode.RangeTable
	ignoreCase      bool
	inverted        bool
}

type anyMatcher position

// errList cumulates the errors found by the parser.
type errList []error

func (e *errList) add(err error) {
	*e = append(*e, err)
}

func (e errList) err() error {
	if len(e) == 0 {
		return nil
	}
	e.dedupe()
	return e
}

func (e *errList) dedupe() {
	var cleaned []error
	set := make(map[string]bool)
	for _, err := range *e {
		if msg := err.Error(); !set[msg] {
			set[msg] = true
			cleaned = append(cleaned, err)
		}
	}
	*e = cleaned
}

func (e errList) Error() string {
	switch len(e) {
	case 0:
		return ""
	case 1:
		return e[0].Error()
	default:
		var buf bytes.Buffer

		for i, err := range e {
			if i > 0 {
				buf.WriteRune('\n')
			}
			buf.WriteString(err.Error())
		}
		return buf.String()
	}
}

// parserError wraps an error with a prefix indicating the rule in which
// the error occurred. The original error is stored in the Inner field.
type parserError struct {
	Inner    error
	pos      position
	prefix   string
	expected []string
}

// Error returns the error message.
func (p *parserError) Error() string {
	return p.prefix + ": " + p.Inner.Error()
}

// newParser creates a parser with the specified input source and options.
func newParser(filename string, b []byte, opts ...Option) *parser {
	stats := Stats{
		ChoiceAltCnt: make(map[string]map[string]int),
	}

	p := &parser{
		filename: filename,
		errs:     new(errList),
		data:     b,
		pt:       savepoint{position: position{line: 1}},
		recover:  true,
		cur: current{
			state:       make(storeDict),
			globalStore: make(storeDict),
		},
		maxFailPos:      position{col: 1, line: 1},
		maxFailExpected: make([]string, 0, 20),
		Stats:           &stats,
		// start rule is rule [0] unless an alternate entrypoint is specified
		entrypoint: g.rules[0].name,
	}
	p.setOptions(opts)

	if p.maxExprCnt == 0 {
		p.maxExprCnt = math.MaxUint64
	}

	return p
}

// setOptions applies the options to the parser.
func (p *parser) setOptions(opts []Option) {
	for _, opt := range opts {
		opt(p)
	}
}

type resultTuple struct {
	v   interface{}
	b   bool
	end savepoint
}

const choiceNoMatch = -1

// Stats stores some statistics, gathered during parsing
type Stats struct {
	// ExprCnt counts the number of expressions processed during parsing
	// This value is compared to the maximum number of expressions allowed
	// (set by the MaxExpressions option).
	ExprCnt uint64

	// ChoiceAltCnt is used to count for each ordered choice expression,
	// which alternative is used how may times.
	// These numbers allow to optimize the order of the ordered choice expression
	// to increase the performance of the parser
	//
	// The outer key of ChoiceAltCnt is composed of the name of the rule as well
	// as the line and the column of the ordered choice.
	// The inner key of ChoiceAltCnt is the number (one-based) of the matching alternative.
	// For each alternative the number of matches are counted. If an ordered choice does not
	// match, a special counter is incremented. The name of this counter is set with
	// the parser option Statistics.
	// For an alternative to be included in ChoiceAltCnt, it has to match at least once.
	ChoiceAltCnt map[string]map[string]int
}

type parser struct {
	filename string
	pt       savepoint
	cur      current

	data []byte
	errs *errList

	depth   int
	recover bool
	debug   bool

	memoize bool
	// memoization table for the packrat algorithm:
	// map[offset in source] map[expression or rule] {value, match}
	memo map[int]map[interface{}]resultTuple

	// rules table, maps the rule identifier to the rule node
	rules map[string]*rule
	// variables stack, map of label to value
	vstack []map[string]interface{}
	// rule stack, allows identification of the current rule in errors
	rstack []*rule

	// parse fail
	maxFailPos            position
	maxFailExpected       []string
	maxFailInvertExpected bool

	// max number of expressions to be parsed
	maxExprCnt uint64
	// entrypoint for the parser
	entrypoint string

	allowInvalidUTF8 bool

	*Stats

	choiceNoMatch string
	// recovery expression stack, keeps track of the currently available recovery expression, these are traversed in reverse
	recoveryStack []map[string]interface{}
}

// push a variable set on the vstack.
func (p *parser) pushV() {
	if cap(p.vstack) == len(p.vstack) {
		// create new empty slot in the stack
		p.vstack = append(p.vstack, nil)
	} else {
		// slice to 1 more
		p.vstack = p.vstack[:len(p.vstack)+1]
	}

	// get the last args set
	m := p.vstack[len(p.vstack)-1]
	if m != nil && len(m) == 0 {
		// empty map, all good
		return
	}

	m = make(map[string]interface{})
	p.vstack[len(p.vstack)-1] = m
}

// pop a variable set from the vstack.
func (p *parser) popV() {
	// if the map is not empty, clear it
	m := p.vstack[len(p.vstack)-1]
	if len(m) > 0 {
		// GC that map
		p.vstack[len(p.vstack)-1] = nil
	}
	p.vstack = p.vstack[:len(p.vstack)-1]
}

// push a recovery expression with its labels to the recoveryStack
func (p *parser) pushRecovery(labels []string, expr interface{}) {
	if cap(p.recoveryStack) == len(p.recoveryStack) {
		// create new empty slot in the stack
		p.recoveryStack = append(p.recoveryStack, nil)
	} else {
		// slice to 1 more
		p.recoveryStack = p.recoveryStack[:len(p.recoveryStack)+1]
	}

	m := make(map[string]interface{}, len(labels))
	for _, fl := range labels {
		m[fl] = expr
	}
	p.recoveryStack[len(p.recoveryStack)-1] = m
}

// pop a recovery expression from the recoveryStack
func (p *parser) popRecovery() {
	// GC that map
	p.recoveryStack[len(p.recoveryStack)-1] = nil

	p.recoveryStack = p.recoveryStack[:len(p.recoveryStack)-1]
}

func (p *parser) print(prefix, s string) string {
	if !p.debug {
		return s
	}

	fmt.Printf("%s %d:%d:%d: %s [%#U]\n",
		prefix, p.pt.line, p.pt.col, p.pt.offset, s, p.pt.rn)
	return s
}

func (p *parser) in(s string) string {
	p.depth++
	return p.print(strings.Repeat(" ", p.depth)+">", s)
}

func (p *parser) out(s string) string {
	p.depth--
	return p.print(strings.Repeat(" ", p.depth)+"<", s)
}

func (p *parser) addErr(err error) {
	p.addErrAt(err, p.pt.position, []string{})
}

func (p *parser) addErrAt(err error, pos position, expected []string) {
	var buf bytes.Buffer
	if p.filename != "" {
		buf.WriteString(p.filename)
	}
	if buf.Len() > 0 {
		buf.WriteString(":")
	}
	buf.WriteString(fmt.Sprintf("%d:%d (%d)", pos.line, pos.col, pos.offset))
	if len(p.rstack) > 0 {
		if buf.Len() > 0 {
			buf.WriteString(": ")
		}
		rule := p.rstack[len(p.rstack)-1]
		if rule.displayName != "" {
			buf.WriteString("rule " + rule.displayName)
		} else {
			buf.WriteString("rule " + rule.name)
		}
	}
	pe := &parserError{Inner: err, pos: pos, prefix: buf.String(), expected: expected}
	p.errs.add(pe)
}

func (p *parser) failAt(fail bool, pos position, want string) {
	// process fail if parsing fails and not inverted or parsing succeeds and invert is set
	if fail == p.maxFailInvertExpected {
		if pos.offset < p.maxFailPos.offset {
			return
		}

		if pos.offset > p.maxFailPos.offset {
			p.maxFailPos = pos
			p.maxFailExpected = p.maxFailExpected[:0]
		}

		if p.maxFailInvertExpected {
			want = "!" + want
		}
		p.maxFailExpected = append(p.maxFailExpected, want)
	}
}

// read advances the parser to the next rune.
func (p *parser) read() {
	p.pt.offset += p.pt.w
	rn, n := utf8.DecodeRune(p.data[p.pt.offset:])
	p.pt.rn = rn
	p.pt.w = n
	p.pt.col++
	if rn == '\n' {
		p.pt.line++
		p.pt.col = 0
	}

	if rn == utf8.RuneError && n == 1 { // see utf8.DecodeRune
		if !p.allowInvalidUTF8 {
			p.addErr(errInvalidEncoding)
		}
	}
}

// restore parser position to the savepoint pt.
func (p *parser) restore(pt savepoint) {
	if p.debug {
		defer p.out(p.in("restore"))
	}
	if pt.offset == p.pt.offset {
		return
	}
	p.pt = pt
}

// Cloner is implemented by any value that has a Clone method, which returns a
// copy of the value. This is mainly used for types which are not passed by
// value (e.g map, slice, chan) or structs that contain such types.
//
// This is used in conjunction with the global state feature to create proper
// copies of the state to allow the parser to properly restore the state in
// the case of backtracking.
type Cloner interface {
	Clone() interface{}
}

// clone and return parser current state.
func (p *parser) cloneState() storeDict {
	if p.debug {
		defer p.out(p.in("cloneState"))
	}

	state := make(storeDict, len(p.cur.state))
	for k, v := range p.cur.state {
		if c, ok := v.(Cloner); ok {
			state[k] = c.Clone()
		} else {
			state[k] = v
		}
	}
	return state
}

// restore parser current state to the state storeDict.
// every restoreState should applied only one time for every cloned state
func (p *parser) restoreState(state storeDict) {
	if p.debug {
		defer p.out(p.in("restoreState"))
	}
	p.cur.state = state
}

// get the slice of bytes from the savepoint start to the current position.
func (p *parser) sliceFrom(start savepoint) []byte {
	return p.data[start.position.offset:p.pt.position.offset]
}

func (p *parser) getMemoized(node interface{}) (resultTuple, bool) {
	if len(p.memo) == 0 {
		return resultTuple{}, false
	}
	m := p.memo[p.pt.offset]
	if len(m) == 0 {
		return resultTuple{}, false
	}
	res, ok := m[node]
	return res, ok
}

func (p *parser) setMemoized(pt savepoint, node interface{}, tuple resultTuple) {
	if p.memo == nil {
		p.memo = make(map[int]map[interface{}]resultTuple)
	}
	m := p.memo[pt.offset]
	if m == nil {
		m = make(map[interface{}]resultTuple)
		p.memo[pt.offset] = m
	}
	m[node] = tuple
}

func (p *parser) buildRulesTable(g *grammar) {
	p.rules = make(map[string]*rule, len(g.rules))
	for _, r := range g.rules {
		p.rules[r.name] = r
	}
}

func (p *parser) parse(g *grammar) (val interface{}, err error) {
	if len(g.rules) == 0 {
		p.addErr(errNoRule)
		return nil, p.errs.err()
	}

	// TODO : not super critical but this could be generated
	p.buildRulesTable(g)

	if p.recover {
		// panic can be used in action code to stop parsing immediately
		// and return the panic as an error.
		defer func() {
			if e := recover(); e != nil {
				if p.debug {
					defer p.out(p.in("panic handler"))
				}
				val = nil
				switch e := e.(type) {
				case error:
					p.addErr(e)
				default:
					p.addErr(fmt.Errorf("%v", e))
				}
				err = p.errs.err()
			}
		}()
	}

	startRule, ok := p.rules[p.entrypoint]
	if !ok {
		p.addErr(errInvalidEntrypoint)
		return nil, p.errs.err()
	}

	p.read() // advance to first rune
	val, ok = p.parseRule(startRule)
	if !ok {
		if len(*p.errs) == 0 {
			// If parsing fails, but no errors have been recorded, the expected values
			// for the farthest parser position are returned as error.
			maxFailExpectedMap := make(map[string]struct{}, len(p.maxFailExpected))
			for _, v := range p.maxFailExpected {
				maxFailExpectedMap[v] = struct{}{}
			}
			expected := make([]string, 0, len(maxFailExpectedMap))
			eof := false
			if _, ok := maxFailExpectedMap["!."]; ok {
				delete(maxFailExpectedMap, "!.")
				eof = true
			}
			for k := range maxFailExpectedMap {
				expected = append(expected, k)
			}
			sort.Strings(expected)
			if eof {
				expected = append(expected, "EOF")
			}
			p.addErrAt(errors.New("no match found, expected: "+listJoin(expected, ", ", "or")), p.maxFailPos, expected)
		}

		return nil, p.errs.err()
	}
	return val, p.errs.err()
}

func listJoin(list []string, sep string, lastSep string) string {
	switch len(list) {
	case 0:
		return ""
	case 1:
		return list[0]
	default:
		return fmt.Sprintf("%s %s %s", strings.Join(list[:len(list)-1], sep), lastSep, list[len(list)-1])
	}
}

func (p *parser) parseRule(rule *rule) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseRule " + rule.name))
	}

	if p.memoize {
		res, ok := p.getMemoized(rule)
		if ok {
			p.restore(res.end)
			return res.v, res.b
		}
	}

	start := p.pt
	p.rstack = append(p.rstack, rule)
	p.pushV()
	val, ok := p.parseExpr(rule.expr)
	p.popV()
	p.rstack = p.rstack[:len(p.rstack)-1]
	if ok && p.debug {
		p.print(strings.Repeat(" ", p.depth)+"MATCH", string(p.sliceFrom(start)))
	}

	if p.memoize {
		p.setMemoized(start, rule, resultTuple{val, ok, p.pt})
	}
	return val, ok
}

func (p *parser) parseExpr(expr interface{}) (interface{}, bool) {
	var pt savepoint

	if p.memoize {
		res, ok := p.getMemoized(expr)
		if ok {
			p.restore(res.end)
			return res.v, res.b
		}
		pt = p.pt
	}

	p.ExprCnt++
	if p.ExprCnt > p.maxExprCnt {
		panic(errMaxExprCnt)
	}

	var val interface{}
	var ok bool
	switch expr := expr.(type) {
	case *actionExpr:
		val, ok = p.parseActionExpr(expr)
	case *andCodeExpr:
		val, ok = p.parseAndCodeExpr(expr)
	case *andExpr:
		val, ok = p.parseAndExpr(expr)
	case *anyMatcher:
		val, ok = p.parseAnyMatcher(expr)
	case *charClassMatcher:
		val, ok = p.parseCharClassMatcher(expr)
	case *choiceExpr:
		val, ok = p.parseChoiceExpr(expr)
	case *labeledExpr:
		val, ok = p.parseLabeledExpr(expr)
	case *litMatcher:
		val, ok = p.parseLitMatcher(expr)
	case *notCodeExpr:
		val, ok = p.parseNotCodeExpr(expr)
	case *notExpr:
		val, ok = p.parseNotExpr(expr)
	case *oneOrMoreExpr:
		val, ok = p.parseOneOrMoreExpr(expr)
	case *recoveryExpr:
		val, ok = p.parseRecoveryExpr(expr)
	case *ruleRefExpr:
		val, ok = p.parseRuleRefExpr(expr)
	case *seqExpr:
		val, ok = p.parseSeqExpr(expr)
	case *stateCodeExpr:
		val, ok = p.parseStateCodeExpr(expr)
	case *throwExpr:
		val, ok = p.parseThrowExpr(expr)
	case *zeroOrMoreExpr:
		val, ok = p.parseZeroOrMoreExpr(expr)
	case *zeroOrOneExpr:
		val, ok = p.parseZeroOrOneExpr(expr)
	default:
		panic(fmt.Sprintf("unknown expression type %T", expr))
	}
	if p.memoize {
		p.setMemoized(pt, expr, resultTuple{val, ok, p.pt})
	}
	return val, ok
}

func (p *parser) parseActionExpr(act *actionExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseActionExpr"))
	}

	start := p.pt
	val, ok := p.parseExpr(act.expr)
	if ok {
		p.cur.pos = start.position
		p.cur.text = p.sliceFrom(start)
		state := p.cloneState()
		actVal, err := act.run(p)
		if err != nil {
			p.addErrAt(err, start.position, []string{})
		}
		p.restoreState(state)

		val = actVal
	}
	if ok && p.debug {
		p.print(strings.Repeat(" ", p.depth)+"MATCH", string(p.sliceFrom(start)))
	}
	return val, ok
}

func (p *parser) parseAndCodeExpr(and *andCodeExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseAndCodeExpr"))
	}

	state := p.cloneState()

	ok, err := and.run(p)
	if err != nil {
		p.addErr(err)
	}
	p.restoreState(state)

	return nil, ok
}

func (p *parser) parseAndExpr(and *andExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseAndExpr"))
	}

	pt := p.pt
	state := p.cloneState()
	p.pushV()
	_, ok := p.parseExpr(and.expr)
	p.popV()
	p.restoreState(state)
	p.restore(pt)

	return nil, ok
}

func (p *parser) parseAnyMatcher(any *anyMatcher) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseAnyMatcher"))
	}

	if p.pt.rn == utf8.RuneError && p.pt.w == 0 {
		// EOF - see utf8.DecodeRune
		p.failAt(false, p.pt.position, ".")
		return nil, false
	}
	start := p.pt
	p.read()
	p.failAt(true, start.position, ".")
	return p.sliceFrom(start), true
}

func (p *parser) parseCharClassMatcher(chr *charClassMatcher) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseCharClassMatcher"))
	}

	cur := p.pt.rn
	start := p.pt

	// can't match EOF
	if cur == utf8.RuneError && p.pt.w == 0 { // see utf8.DecodeRune
		p.failAt(false, start.position, chr.val)
		return nil, false
	}

	if chr.ignoreCase {
		cur = unicode.ToLower(cur)
	}

	// try to match in the list of available chars
	for _, rn := range chr.chars {
		if rn == cur {
			if chr.inverted {
				p.failAt(false, start.position, chr.val)
				return nil, false
			}
			p.read()
			p.failAt(true, start.position, chr.val)
			return p.sliceFrom(start), true
		}
	}

	// try to match in the list of ranges
	for i := 0; i < len(chr.ranges); i += 2 {
		if cur >= chr.ranges[i] && cur <= chr.ranges[i+1] {
			if chr.inverted {
				p.failAt(false, start.position, chr.val)
				return nil, false
			}
			p.read()
			p.failAt(true, start.position, chr.val)
			return p.sliceFrom(start), true
		}
	}

	// try to match in the list of Unicode classes
	for _, cl := range chr.classes {
		if unicode.Is(cl, cur) {
			if chr.inverted {
				p.failAt(false, start.position, chr.val)
				return nil, false
			}
			p.read()
			p.failAt(true, start.position, chr.val)
			return p.sliceFrom(start), true
		}
	}

	if chr.inverted {
		p.read()
		p.failAt(true, start.position, chr.val)
		return p.sliceFrom(start), true
	}
	p.failAt(false, start.position, chr.val)
	return nil, false
}

func (p *parser) incChoiceAltCnt(ch *choiceExpr, altI int) {
	choiceIdent := fmt.Sprintf("%s %d:%d", p.rstack[len(p.rstack)-1].name, ch.pos.line, ch.pos.col)
	m := p.ChoiceAltCnt[choiceIdent]
	if m == nil {
		m = make(map[string]int)
		p.ChoiceAltCnt[choiceIdent] = m
	}
	// We increment altI by 1, so the keys do not start at 0
	alt := strconv.Itoa(altI + 1)
	if altI == choiceNoMatch {
		alt = p.choiceNoMatch
	}
	m[alt]++
}

func (p *parser) parseChoiceExpr(ch *choiceExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseChoiceExpr"))
	}

	for altI, alt := range ch.alternatives {
		// dummy assignment to prevent compile error if optimized
		_ = altI

		state := p.cloneState()

		p.pushV()
		val, ok := p.parseExpr(alt)
		p.popV()
		if ok {
			p.incChoiceAltCnt(ch, altI)
			return val, ok
		}
		p.restoreState(state)
	}
	p.incChoiceAltCnt(ch, choiceNoMatch)
	return nil, false
}

func (p *parser) parseLabeledExpr(lab *labeledExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseLabeledExpr"))
	}

	p.pushV()
	val, ok := p.parseExpr(lab.expr)
	p.popV()
	if ok && lab.label != "" {
		m := p.vstack[len(p.vstack)-1]
		m[lab.label] = val
	}
	return val, ok
}

func (p *parser) parseLitMatcher(lit *litMatcher) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseLitMatcher"))
	}

	ignoreCase := ""
	if lit.ignoreCase {
		ignoreCase = "i"
	}
	val := fmt.Sprintf("%q%s", lit.val, ignoreCase)
	start := p.pt
	for _, want := range lit.val {
		cur := p.pt.rn
		if lit.ignoreCase {
			cur = unicode.ToLower(cur)
		}
		if cur != want {
			p.failAt(false, start.position, val)
			p.restore(start)
			return nil, false
		}
		p.read()
	}
	p.failAt(true, start.position, val)
	return p.sliceFrom(start), true
}

func (p *parser) parseNotCodeExpr(not *notCodeExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseNotCodeExpr"))
	}

	state := p.cloneState()

	ok, err := not.run(p)
	if err != nil {
		p.addErr(err)
	}
	p.restoreState(state)

	return nil, !ok
}

func (p *parser) parseNotExpr(not *notExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseNotExpr"))
	}

	pt := p.pt
	state := p.cloneState()
	p.pushV()
	p.maxFailInvertExpected = !p.maxFailInvertExpected
	_, ok := p.parseExpr(not.expr)
	p.maxFailInvertExpected = !p.maxFailInvertExpected
	p.popV()
	p.restoreState(state)
	p.restore(pt)

	return nil, !ok
}

func (p *parser) parseOneOrMoreExpr(expr *oneOrMoreExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseOneOrMoreExpr"))
	}

	var vals []interface{}

	for {
		p.pushV()
		val, ok := p.parseExpr(expr.expr)
		p.popV()
		if !ok {
			if len(vals) == 0 {
				// did not match once, no match
				return nil, false
			}
			return vals, true
		}
		vals = append(vals, val)
	}
}

func (p *parser) parseRecoveryExpr(recover *recoveryExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseRecoveryExpr (" + strings.Join(recover.failureLabel, ",") + ")"))
	}

	p.pushRecovery(recover.failureLabel, recover.recoverExpr)
	val, ok := p.parseExpr(recover.expr)
	p.popRecovery()

	return val, ok
}

func (p *parser) parseRuleRefExpr(ref *ruleRefExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseRuleRefExpr " + ref.name))
	}

	if ref.name == "" {
		panic(fmt.Sprintf("%s: invalid rule: missing name", ref.pos))
	}

	rule := p.rules[ref.name]
	if rule == nil {
		p.addErr(fmt.Errorf("undefined rule: %s", ref.name))
		return nil, false
	}
	return p.parseRule(rule)
}

func (p *parser) parseSeqExpr(seq *seqExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseSeqExpr"))
	}

	vals := make([]interface{}, 0, len(seq.exprs))

	pt := p.pt
	state := p.cloneState()
	for _, expr := range seq.exprs {
		val, ok := p.parseExpr(expr)
		if !ok {
			p.restoreState(state)
			p.restore(pt)
			return nil, false
		}
		vals = append(vals, val)
	}
	return vals, true
}

func (p *parser) parseStateCodeExpr(state *stateCodeExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseStateCodeExpr"))
	}

	err := state.run(p)
	if err != nil {
		p.addErr(err)
	}
	return nil, true
}

func (p *parser) parseThrowExpr(expr *throwExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseThrowExpr"))
	}

	for i := len(p.recoveryStack) - 1; i >= 0; i-- {
		if recoverExpr, ok := p.recoveryStack[i][expr.label]; ok {
			if val, ok := p.parseExpr(recoverExpr); ok {
				return val, ok
			}
		}
	}

	return nil, false
}

func (p *parser) parseZeroOrMoreExpr(expr *zeroOrMoreExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseZeroOrMoreExpr"))
	}

	var vals []interface{}

	for {
		p.pushV()
		val, ok := p.parseExpr(expr.expr)
		p.popV()
		if !ok {
			return vals, true
		}
		vals = append(vals, val)
	}
}

func (p *parser) parseZeroOrOneExpr(expr *zeroOrOneExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseZeroOrOneExpr"))
	}

	p.pushV()
	val, _ := p.parseExpr(expr.expr)
	p.popV()
	// whether it matched or not, consider it a match
	return val, true
}

func rangeTable(class string) *unicode.RangeTable {
	if rt, ok := unicode.Categories[class]; ok {
		return rt
	}
	if rt, ok := unicode.Properties[class]; ok {
		return rt
	}
	if rt, ok := unicode.Scripts[class]; ok {
		return rt
	}

	// cannot happen
	panic(fmt.Sprintf("invalid Unicode class: %s", class))
}
